### ISSUE TITLE
Backend query - minden fuvaros lekérése (paginated)

### ISSUE THREAD

**Issue by hajdun** [erosb/etesdadokit#14]
Listázza minden fuvaros összes adatát (főleg az elérhetőség kell)

**Comment by fhery021** [comment]
Kérem a 3. oldalt és egy oldal 50 elemet tartalmaz:
`localhost:8080/offer/transport/page?pageNumber=2&pageSize=50`
Az oldalak 0-tól vannak számozva (0 az első oldal, 1 a második, stb.)

`localhost:8080/offer/transport/page `
Visszaadja az első 25-öt pageNumber és pageSize hiányában
