### ISSUE TITLE
Koordinátori felülethez UI terv készítése

### ISSUE THREAD

**Issue by erosb** [erosb/etesdadokit#5]
A specifikációban levő [user scenario](https://github.com/erosb/etesdadokit/blob/master/SPEC.md#kisz%C3%A1ll%C3%ADt%C3%A1si-tervez%C5%91-fel%C3%BClet)-t kell támogatnia.

**Comment by kicsipixel** [comment]
Done: https://www.figma.com/proto/4FNASz7OJfaffwsxbvZCgL/Koordinator?node-id=1%3A2&viewport=-843%2C387%2C1&scaling=min-zoom
